# Generated by Django 4.1.1 on 2022-09-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_alter_vacancy_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errors',
            old_name='datat',
            new_name='data',
        ),
    ]
